### ISSUE TITLE
Make fails on Windows 10 with MSYS2 MinGW64 

### ISSUE THREAD

**Issue by yogeshrao** [openvenues/libpostal#501]
Hi!

I Initially was following the instructions as part of Readme on installing libpostal on Windows 10 and eventually realized that its perhaps out of date and the new instructions are available as part of PR by @batterseapower [here](https://github.com/openvenues/pypostal/pull/39/commits/a234e69a47b5edf7e1f0579637ae5c2db33feaa0) and few people have found success with it.

My installation seems failing at make command. Below are the logs 

$ make
make  all-recursive
make[1]: Entering directory '/home/raoy/libpostal'
Making all in src
make[2]: Entering directory '/home/raoy/libpostal/src'
/bin/sh ../libtool  --tag=CC   --mode=link x86_64-w64-mingw32-gcc -Wall -Wextra -Wno-unused-function -Wformat -Werror=format-security -Winit-self -Wno-sign-compare -DLIBPOSTAL_DATA_DIR='"/c/dataset/libpostal-data/libpostal"' -g -mfpmath=sse -msse2 -DUSE_SSE -g -O2 -O2 -D LIBPOSTAL_EXPORTS  -version-info 1:1:0 -no-undefined -L/usr/local/lib -o libpostal.la -rpath /mingw64/lib libpostal_la-strndup.lo libpostal_la-libpostal.lo libpostal_la-expand.lo libpostal_la-address_dictionary.lo libpostal_la-transliterate.lo libpostal_la-tokens.lo libpostal_la-trie.lo libpostal_la-trie_search.lo libpostal_la-trie_utils.lo libpostal_la-string_utils.lo libpostal_la-file_utils.lo utf8proc/libpostal_la-utf8proc.lo libpostal_la-normalize.lo libpostal_la-numex.lo libpostal_la-features.lo libpostal_la-unicode_scripts.lo libpostal_la-address_parser.lo libpostal_la-address_parser_io.lo libpostal_la-averaged_perceptron.lo libpostal_la-crf.lo libpostal_la-crf_context.lo libpostal_la-sparse_matrix.lo libpostal_la-averaged_perceptron_tagger.lo libpostal_la-graph.lo libpostal_la-graph_builder.lo libpostal_la-language_classifier.lo libpostal_la-language_features.lo libpostal_la-logistic_regression.lo libpostal_la-logistic.lo libpostal_la-minibatch.lo libpostal_la-float_utils.lo libpostal_la-ngrams.lo libpostal_la-place.lo libpostal_la-near_dupe.lo libpostal_la-double_metaphone.lo geohash/libpostal_la-geohash.lo libpostal_la-dedupe.lo libpostal_la-string_similarity.lo libpostal_la-acronyms.lo libpostal_la-soft_tfidf.lo libpostal_la-jaccard.lo libscanner.la
libtool: link: rm -fr  .libs/libpostal.dll.a
libtool: link: x86_64-w64-mingw32-gcc -shared  .libs/libpostal_la-strndup.o .libs/libpostal_la-libpostal.o .libs/libpostal_la-expand.o .libs/libpostal_la-address_dictionary.o .libs/libpostal_la-transliterate.o .libs/libpostal_la-tokens.o .libs/libpostal_la-trie.o .libs/libpostal_la-trie_search.o .libs/libpostal_la-trie_utils.o .libs/libpostal_la-string_utils.o .libs/libpostal_la-file_utils.o utf8proc/.libs/libpostal_la-utf8proc.o .libs/libpostal_la-normalize.o .libs/libpostal_la-numex.o .libs/libpostal_la-features.o .libs/libpostal_la-unicode_scripts.o .libs/libpostal_la-address_parser.o .libs/libpostal_la-address_parser_io.o .libs/libpostal_la-averaged_perceptron.o .libs/libpostal_la-crf.o .libs/libpostal_la-crf_context.o .libs/libpostal_la-sparse_matrix.o .libs/libpostal_la-averaged_perceptron_tagger.o .libs/libpostal_la-graph.o .libs/libpostal_la-graph_builder.o .libs/libpostal_la-language_classifier.o .libs/libpostal_la-language_features.o .libs/libpostal_la-logistic_regression.o .libs/libpostal_la-logistic.o .libs/libpostal_la-minibatch.o .libs/libpostal_la-float_utils.o .libs/libpostal_la-ngrams.o .libs/libpostal_la-place.o .libs/libpostal_la-near_dupe.o .libs/libpostal_la-double_metaphone.o geohash/.libs/libpostal_la-geohash.o .libs/libpostal_la-dedupe.o .libs/libpostal_la-string_similarity.o .libs/libpostal_la-acronyms.o .libs/libpostal_la-soft_tfidf.o .libs/libpostal_la-jaccard.o  -Wl,--whole-archive ./.libs/libscanner.a -Wl,--no-whole-archive  -L/usr/local/lib  -g -mfpmath=sse -msse2 -g -O2 -O2   -o .libs/libpostal-1.dll -Wl,--enable-auto-image-base -Xlinker --out-implib -Xlinker .libs/libpostal.dll.a
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-expand.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-expand.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-expand.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-address_dictionary.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-address_dictionary.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-address_dictionary.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-transliterate.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-transliterate.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-transliterate.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-tokens.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-tokens.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-tokens.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-trie.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-trie.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-trie.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-trie_search.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-trie_search.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-trie_search.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-trie_utils.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-trie_utils.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-trie_utils.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-string_utils.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-string_utils.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-string_utils.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-file_utils.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-file_utils.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-file_utils.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-normalize.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-normalize.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-normalize.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-numex.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-numex.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-numex.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-features.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-features.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-features.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-unicode_scripts.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-unicode_scripts.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-unicode_scripts.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-address_parser.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-address_parser.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-address_parser.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-address_parser_io.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-address_parser_io.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-address_parser_io.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-averaged_perceptron.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-averaged_perceptron.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-averaged_perceptron.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-crf.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-crf.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-crf.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-crf_context.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-crf_context.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-crf_context.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-sparse_matrix.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-sparse_matrix.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-sparse_matrix.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-averaged_perceptron_tagger.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-averaged_perceptron_tagger.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-averaged_perceptron_tagger.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-graph.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-graph.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-graph.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-graph_builder.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-graph_builder.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-graph_builder.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-language_classifier.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-language_classifier.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-language_classifier.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-language_features.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-language_features.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-language_features.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-logistic_regression.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-logistic_regression.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-logistic_regression.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-logistic.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-logistic.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-logistic.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-minibatch.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-minibatch.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-minibatch.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-ngrams.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-ngrams.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-ngrams.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-place.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-place.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-place.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-near_dupe.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-near_dupe.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-near_dupe.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-double_metaphone.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-double_metaphone.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-double_metaphone.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-dedupe.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-dedupe.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-dedupe.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-string_similarity.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-string_similarity.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-string_similarity.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-acronyms.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-acronyms.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-acronyms.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-soft_tfidf.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-soft_tfidf.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-soft_tfidf.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-jaccard.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-jaccard.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .libs/libpostal_la-jaccard.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./.libs/libscanner.a(libscanner_la-drand48.o):C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./.libs/libscanner.a(libscanner_la-drand48.o):C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./.libs/libscanner.a(libscanner_la-drand48.o):C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./.libs/libscanner.a(libscanner_la-scanner.o):C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:32: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./.libs/libscanner.a(libscanner_la-scanner.o):C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: multiple definition of `_rand48_mult'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:34: first defined here
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./.libs/libscanner.a(libscanner_la-scanner.o):C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of `_rand48_add'; .libs/libpostal_la-libpostal.o:C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: first defined here
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:1026: libpostal.la] Error 1
make[2]: Leaving directory '/home/raoy/libpostal/src'
make[1]: *** [Makefile:458: all-recursive] Error 1
make[1]: Leaving directory '/home/raoy/libpostal'
make: *** [Makefile:367: all] Error 2

Can anyone help solve this error ? or am i following wrong instructions to begin with.

Thanks in advance...

Regards,
-Yogesh

**Comment by philhutch50** [comment]
Have a look at this

https://github.com/marco110/LibPostalNet_1/issues/3

I managed to get it to work.

**Comment by kyrill007** [comment]
I have the same problem trying to build it on Win 10.  It looks like Yogesh and I are doing exactly what

marco110/LibPostalNet_1#3

is suggesting.  Any help would be greatly appreciated!

**Comment by philhutch50** [comment]
@kyrill007 You can get it to build, if you follow my comments in the tagged post above it will work.
Good luck
Regards
Phil

**Comment by kyrill007** [comment]
That's literally what Yogesh and I are following... It will not build. I mean what are those instructions? Use 64-bit version of msys? yes, that's what I am using. 

Btw, this kind of log messages in msys build:
 C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./.libs/libscanner.a(libscanner_la-scanner.o):C:\msys64\home\raoy\libpostal\src/klib/drand48.h:36: multiple definition of _rand48_add'; 

(and I get them too) look suspicious...

**Comment by philhutch50** [comment]
Here is a link to my compiled 64 bit dll

https://www.dropbox.com/t/UY9QWKCbfqpPVjKq

The data is on my c drive in the libpostal directory.
Regards
Phil

**Comment by kyrill007** [comment]
Thanks, Phil. Did you *just* build it or is this from 2018?

**Comment by philhutch50** [comment]
No this is when I built it - but it works fine.

**Comment by kyrill007** [comment]
Did you by any chance get to build *jpostal* on Windows too? The problem is that I can't get jpostal to build against your library because its Makefile wants pkg-config to find your library first... :(

**Comment by philhutch50** [comment]
No I'm sorry I didn't, I just use libpostal. I code in Delphi so have a
unit that interfaces into the DLL.

**Comment by philhutch50** [comment]
have you done this as well

Also, it's worth mentioning in Readme that we need to replace the libpostal.def with the https://raw.githubusercontent.com/openvenues/libpostal/216c947e37cd3d885b2a29b5b330406b7df739a4/libpostal.def

**Comment by Forale** [comment]
@philhutch50 @kyrill007 I am having the same issue on windows 10. Could you please share DLL? (link to dropbox does not work for me https://www.dropbox.com/t/UY9QWKCbfqpPVjKq)

**Comment by philhutch50** [comment]
https://github.com/openvenues/libpostal/issues/514

This is the solution :-)

**Comment by kyrill007** [comment]
No. #514 is not the solution. The binaries still don't build on windows. Same error.

**Comment by qwerty2k** [comment]
just wanted to ask if anyone had a solution, im having the exact same issue on windows 10.

**Comment by kyrill007** [comment]
I have fixed this issue and create a pull request.

**Comment by qwerty2k** [comment]
> I have fixed this issue and create a pull request.

Thank you! I built it from your repo and it build fine, appreciate the effort, thank you 👍

**Comment by kyrill007** [comment]
@albarrentine can we merge this pull request into the main tree? It would enable windows-based builds. Pretty important I would think.

**Comment by RILUCK** [comment]
@kyrill007 Can you please share what changes did you made? I'm still getting the error in "make -j4" step.

**Comment by XtineInWa** [comment]
I'm still having problems with this. Can anyone chime in and tell me how to make this work? 
I'm still getting this error during the make process of building libpostal on windows:
tar (child): Cannot connect to C: resolve failed
